### PR TITLE
Merge pull request #2 from dixi83/master

### PR DESCRIPTION
**Pull request by dixi83**
command path can now contain spaces.

### CODE REVIEW

**Comment by Kachiarginis** [comment]
Hi, I've tried to use your library , but in php7.4 and VSCode i have many errors showing in VScode. I would like to know if i have to install phosphor7 library or it uses only simple require command (like in your examples)?

**Comment by dixi83** [comment]
what does simple-multi-threader has to do with phosphor7? I do not maintain this anymore and it has been over 3 years since I used it I think in PHP7.3 
I think this repo should be archived...

**Comment by Kachiarginis** [comment]
Thanks for answer. Actually i'm new here in github, did not found where to write a question :) just found some place where to write the message for You. Anyway, just searching some tool to read/write from Simatic PLC in the web platform. Maybe You could suggest some stuff ? Thanks in advance.

**Comment by dixi83** [comment]
No Worries!
For reading/writing to a S7 PLC you will not need this library 😉 

Checkout https://github.com/PHP-S7/phosphor7 I am the maintainer and if you have question I am happy to help. Post your questions in the "Discussions" and if you really think we are facing a bug here, then post an "Issue". but please post the error messages you'll get as well. But It is optimized for PHP8 nowadays. PHP7.x is deprecated and not supported anymore so please use PHP8.

**Pull request merged**
